CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`USER`	VARCHAR(100)	NULL
);

CREATE TABLE `RESPOND` (
	`RESPOND_ID`	VARCHAR(50)	NOT NULL,
	`PK_QUIZ_ID`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `QUIZS` (
	`PK_QUIZ_ID`	VARCHAR(50)	NOT NULL,
	`CONTENT`	VARCHAR(255)	NULL,
	`POINTS`	DECIMAL(20,0)	NULL,
	`CORRECT`	VARCHAR(10)	NULL,
	`NUMBERS`	DECIMAL(20,0)	NULL,
	`FK_QUIZ_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `RESPOND` ADD CONSTRAINT `PK_RESPOND` PRIMARY KEY (
	`RESPOND_ID`,
	`PK_QUIZ_ID`,
	`USER_ID`
);

ALTER TABLE `QUIZS` ADD CONSTRAINT `PK_QUIZS` PRIMARY KEY (
	`PK_QUIZ_ID`
);

ALTER TABLE `RESPOND` ADD CONSTRAINT `FK_QUIZS_TO_RESPOND_1` FOREIGN KEY (
	`PK_QUIZ_ID`
)
REFERENCES `QUIZS` (
	`PK_QUIZ_ID`
);

ALTER TABLE `RESPOND` ADD CONSTRAINT `FK_USER_TO_RESPOND_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);
