CREATE TABLE `CAR_INFO` (
	`PK_CAR_ID`	VARCHAR(50)	NOT NULL,
	`CAR_NAME`	VARCHAR(255)	NULL,
	`FK_COMMON_CODES_COMPANY`	VARCHAR(50)	NULL,
	`FK_COMMON_CODES_YEARS`	VARCHAR(50)	NULL
);

CREATE TABLE `COMMON_CODES` (
	`FK_COMMON_CODES`	VARCHAR(50)	NOT NULL,
	`PART_NAME`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `PK_CAR_INFO` PRIMARY KEY (
	`PK_CAR_ID`
);

ALTER TABLE `COMMON_CODES` ADD CONSTRAINT `PK_COMMON_CODES` PRIMARY KEY (
	`FK_COMMON_CODES`
);